connector.name=iceberg
iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://spark101:9083
hive.config.resources=/opt/module/hadoop/etc/hadoop/core-site.xml,/opt/module/hadoop/etc/hadoop/hdfs-site.xml
